r"""
Write the palette out as CSS custom properties.

    runners\make-theme.bat            write web/src/theme.generated.css
    runners\make-theme.bat --check    fail if it is out of date
    runners\make-theme.bat --print    write nothing, show what it would write

`libraries/vrfview/theme.py` stays the one place the colours are decided, and
this generates from it, on the same principle as `make_icons.py`: a value the
interface shows should have one home, and a second copy in another language is
a second thing to forget to change.

It matters more here than a duplicated hex string usually would, because the
palette carries an argument.  The brief names its red ATK and its blue DEF, and
this project does not adopt those *meanings* -- which team attacked is not
recoverable, since spike events carry no actor ID -- so the hues are the
brief's and the labels say A and B.  That reasoning lives beside the constants
in `theme.py`, where anyone changing them will read it.  Copying the values
into a stylesheet by hand would leave the values in one place and the reason in
another.

The generated file is committed, so a checkout builds without running this, and
`tests/test_theme.py` asserts it is current.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from vrfview import theme

OUT = Path("web") / "src" / "theme.generated.css"

HEADER = """/*
 * Generated by scripts/make_theme.py from libraries/vrfview/theme.py.
 * Do not edit: run `runners\\make-theme.bat` instead.
 *
 * Team colours are blue and coral, deliberately not Valorant's attacker red
 * and defender green.  Which team attacked is not recoverable from a replay --
 * spike events carry no actor ID -- so using the sides' familiar colours would
 * assert something the data does not support.  Every label that shows these
 * says A or B.
 */
"""

# Name in theme.py -> custom property, in the order they are written out.  A
# list rather than a sweep of the module so adding a constant is a deliberate
# act: not everything in theme.py is a colour the page needs.
COLOURS = (
    ("APP_BG", "--app-bg"),
    ("CARD_BG", "--card-bg"),
    ("CARD_HOVER", "--card-hover"),
    ("TEXT_PRIMARY", "--text-primary"),
    ("TEXT_MUTED", "--text-muted"),
    ("BORDER", "--border"),
    ("TOOLTIP_BG", "--tooltip-bg"),
    ("ACCENT_A", "--accent-a"),
    ("ACCENT_B", "--accent-b"),
    ("ACCENT_OK", "--accent-ok"),
    ("ACCENT", "--accent"),
    ("BACKGROUND", "--canvas-bg"),
    ("PANEL", "--panel"),
    ("PANEL_EDGE", "--panel-edge"),
    ("TEXT", "--canvas-text"),
    ("MUTED", "--muted"),
    ("FAINT", "--faint"),
    ("ULT", "--ult"),
    ("SPIKE_ARMED", "--spike-armed"),
    ("SPIKE_SAFE", "--spike-safe"),
    ("SPIKE_BOOM", "--spike-boom"),
    ("PLAYHEAD", "--playhead"),
)


def render() -> str:
    """The stylesheet this palette produces."""
    lines = [HEADER, ":root {"]
    lines += [f"  {prop}: {getattr(theme, name)};" for name, prop in COLOURS]
    lines.append("")
    lines.append("  /* Team A and team B, inferred; never attacker and defender. */")
    for team, colour in sorted(theme.TEAM_COLOURS.items()):
        suffix = {"A": "a", "B": "b"}.get(team, "unknown")
        lines.append(f"  --team-{suffix}: {colour};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="make-theme",
        description="Write the palette out as CSS custom properties.",
    )
    parser.add_argument("--out", default=str(OUT), help=f"default {OUT}")
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit non-zero if the file is out of date",
    )
    parser.add_argument(
        "--print",
        dest="show",
        action="store_true",
        help="write nothing; print what would be written",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    wanted = render()
    out = Path(args.out)

    if args.show:
        print(wanted, end="")
        return 0

    if args.check:
        current = out.read_text(encoding="utf-8") if out.is_file() else ""
        if current == wanted:
            print(f"{out} is current")
            return 0
        print(f"{out} is out of date; run runners\\make-theme.bat")
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(wanted, encoding="utf-8")
    print(f"wrote {out} ({len(COLOURS) + len(theme.TEAM_COLOURS)} colours)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
